# Generated by Django 4.0.4 on 2022-05-09 05:43

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_Description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('long_description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='Treatmentimage')),
                ('icon_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='TreatmentImageGallery')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentapp.treatment')),
            ],
        ),
    ]
