# Generated by Django 4.0.4 on 2022-05-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmentimagegallery',
            old_name='image',
            new_name='after_image',
        ),
        migrations.AddField(
            model_name='treatmentimagegallery',
            name='before_image',
            field=models.ImageField(blank=True, upload_to='TreatmentImageGallery'),
        ),
    ]
