# Generated by Django 3.2.12 on 2022-05-10 04:31

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dentapp', '0003_alter_treatmentimagegallery_before_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='MembershipImg')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('membership_plans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentapp.membershipplan')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='MembershipImg')),
                ('membership_plans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentapp.membershipplan')),
            ],
        ),
    ]
