# Generated by Django 3.2.12 on 2022-05-10 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentapp', '0004_membershipbannerimage_membershipdescription_membershipplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipdescription',
            name='membership_plans',
        ),
        migrations.DeleteModel(
            name='MembershipBannerImage',
        ),
        migrations.DeleteModel(
            name='MembershipDescription',
        ),
        migrations.DeleteModel(
            name='MembershipPlan',
        ),
    ]
