# Generated by Django 3.2.12 on 2022-05-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentapp', '0007_patientsafety'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='patientsafety',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
