# Generated by Django 3.2.12 on 2022-05-19 08:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depertment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depertment_name', models.CharField(blank=True, max_length=500, null=True)),
                ('activate_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctorprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('degree1', models.CharField(max_length=100)),
                ('avg_duration_min', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('avg_load_per_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('marriage_status', models.BooleanField()),
                ('date_of_birth', models.DateField()),
                ('join_date', models.DateField()),
                ('active_status', models.BooleanField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('religion', models.CharField(choices=[('Muslim', 'Muslim'), ('Christian', 'Christian'), ('Hindu', 'Hindu'), ('Buddhism', 'Buddhism'), ('Other', 'Other')], max_length=100)),
                ('weekly', multiselectfield.db.fields.MultiSelectField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('connection_depertment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depertment', to='appointments.depertment')),
            ],
        ),
    ]
