# Generated by Django 3.2.12 on 2022-05-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='degree1',
            new_name='degree',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='doctor_name',
            field=models.CharField(default='doc1', max_length=150),
            preserve_default=False,
        ),
    ]
