# Generated by Django 3.2.12 on 2022-05-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20220521_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patientschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.IntegerField()),
                ('doc_id', models.IntegerField()),
                ('date_value', models.CharField(max_length=10)),
                ('timeslotset', models.CharField(max_length=10)),
            ],
        ),
    ]
