# Generated by Django 3.2.12 on 2022-05-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_patientschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientschedule',
            name='email',
            field=models.EmailField(default='25-5-2022', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientschedule',
            name='fullname',
            field=models.CharField(default='abu f', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientschedule',
            name='message',
            field=models.TextField(default='dfgh gghh'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientschedule',
            name='phone',
            field=models.CharField(default='0174584', max_length=15),
            preserve_default=False,
        ),
    ]
