# Generated by Django 3.2.12 on 2022-05-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_patientschedule_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientschedule',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='patientschedule',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
