# Generated by Django 3.2.12 on 2022-05-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_auto_20220522_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='image',
            field=models.ImageField(default='doctorprofile/default.jpg', upload_to='doctorprofile'),
        ),
    ]
